version: "3.7"
services:
  app:
    container_name: api
    image: coin-calculator
    build: ./
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: coin-calculator
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:latest
    restart: on-failure
    ports:
      - "6379:6379"

volumes:
  postgres: